[versions]
jvmram = "1.0.3"
slf4j = "2.0.17"
jna = "5.16.0"

protobuf = "3.25.8"
grpc = "1.78.0"

[libraries]
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

jspecify = "org.jspecify:jspecify:1.0.0"

jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }
jna-platform = { module = "net.java.dev.jna:jna-platform", version.ref = "jna" }

grpc-protobuf = { module = "io.grpc:grpc-protobuf", version.ref = "grpc" }
grpc-services = { module = "io.grpc:grpc-services", version.ref = "grpc" }
grpc-netty-shaded = { module = "io.grpc:grpc-netty-shaded", version.ref = "grpc" }

[plugins]
jlink  = "org.beryx.jlink:3.2.0"
protobuf = "com.google.protobuf:0.9.6"
